export interface Book {
  id: string
  title: string
  author: string
  price: number
  cover_url: string | null
  description: string | null
  condition: 'novo' | 'seminovo' | 'usado'
  genre: string | null
  available: boolean
  created_at: string
  updated_at: string
}

export interface BookFormData {
  title: string
  author: string
  price: number
  cover_url: string | null
  description: string | null
  condition: 'novo' | 'seminovo' | 'usado'
  genre: string | null
  available: boolean
}

// Dados de exemplo para fallback local
export const sampleBooks: Book[] = [
  {
    id: '1',
    title: 'O Pequeno Principe',
    author: 'Antoine de Saint-Exupery',
    price: 25.00,
    cover_url: null,
    description: 'Um classico da literatura mundial sobre amizade e amor.',
    condition: 'seminovo',
    genre: 'Infantil',
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Dom Casmurro',
    author: 'Machado de Assis',
    price: 18.00,
    cover_url: null,
    description: 'A historia de Bentinho e Capitu, um dos maiores classicos brasileiros.',
    condition: 'usado',
    genre: 'Romance',
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Harry Potter e a Pedra Filosofal',
    author: 'J.K. Rowling',
    price: 35.00,
    cover_url: null,
    description: 'O primeiro livro da saga do bruxo mais famoso do mundo.',
    condition: 'seminovo',
    genre: 'Fantasia',
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'A Revolucao dos Bichos',
    author: 'George Orwell',
    price: 22.00,
    cover_url: null,
    description: 'Uma fabula satirica sobre poder e corrupcao.',
    condition: 'usado',
    genre: 'Ficcao',
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Tudo que é Sólido Desmancha no Ar - A aventura da modernidade',
    author: 'Marshall Berman',
    price: 18.00,
    cover_url: null,
    description: 'Uma reflexao sobre modernidade em um classico do pensamento social.',
    condition: 'seminovo',
    genre: 'Filosofia',
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Uma Cura Espiritual',
    author: 'Adolfo Marques da Costa',
    price: 7.00,
    cover_url: null,
    description: 'Uma obra sobre busca interior e bem-estar espiritual.',
    condition: 'seminovo',
    genre: 'Espiritualidade',
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    title: 'Uma Vida',
    author: 'Guy de Maupassant',
    price: 15.00,
    cover_url: null,
    description: 'Um romance intenso de Maupassant sobre amor e destino.',
    condition: 'seminovo',
    genre: 'Romance',
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    title: 'Viena: guia visual',
    author: 'Folha de S. Paulo',
    price: 15.00,
    cover_url: null,
    description: 'Um guia ilustrado para a cidade de Viena.',
    condition: 'seminovo',
    genre: 'Viagem',
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '9',
    title: 'acho que nao mandei tudo 1000 Perguntas e Respostas de Direito Constitucional',
    author: 'José Cretella Júnior e José Cretella Neto',
    price: 15.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '10',
    title: '120 minutos para blindar seu casamento',
    author: 'Renato & Cristiane Cardoso',
    price: 8.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '11',
    title: '14 lições da filosofia Yogue',
    author: 'Yogue Ramacharaca',
    price: 5.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '12',
    title: 'A Arte da Felicidade: um manual para a vida',
    author: 'Dalai Lama e Howard C. Cutler',
    price: 15.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '13',
    title: 'A Arte da Prudência',
    author: 'Baltasar Gracián',
    price: 10.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '14',
    title: 'A Assinatura de Todas as Coisas',
    author: 'Elizabeth Gilbert',
    price: 32.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '15',
    title: 'A Carta do Descobrimento: ao Rei D. Manuel',
    author: 'Pero Vaz de Caminha',
    price: 8.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '16',
    title: 'A Cartuxa de Parma',
    author: 'Stendhal',
    price: 25.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '17',
    title: 'A Ciência da Auto Realização',
    author: 'A. C. Bhaktivedanta Swami Prabhupada',
    price: 8.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '18',
    title: 'A Ciência da Cura Psíquica: um suplemento à Hatha-Yoga',
    author: 'Yogue Ramacharaca',
    price: 9.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '19',
    title: 'A Consciência de Zeno',
    author: 'Italo Svevo',
    price: 25.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '20',
    title: 'A Dama das Camélias',
    author: 'Alexandre Dumas Filho',
    price: 25.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '21',
    title: 'A Filha',
    author: 'Jane Shemilt',
    price: 10.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '22',
    title: 'A Hora da Verdade: o clássico sobre liderança que revolucionou a administração de empresas',
    author: 'Jan Carlzon',
    price: 22.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '23',
    title: 'A Lei Universal da Atração: aprendendo a conquistar o que você deseja',
    author: 'Esther & Jerry Hicks',
    price: 12.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '24',
    title: 'A Linha de Sombra',
    author: 'Joseph Conrad',
    price: 10.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '25',
    title: 'A Lista de Brett',
    author: 'Lori Nelson Spielman',
    price: 28.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '26',
    title: 'A Menina que Roubava Livros',
    author: 'Markus Zusak',
    price: 25.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '27',
    title: 'A Meta da Empresa: seu alcance sem mistérios',
    author: 'Reinaldo Guerreiro',
    price: 12.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '28',
    title: 'A Metamorfose',
    author: 'Franz Kafka',
    price: 18.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '29',
    title: 'A Teia da Vida',
    author: 'Fritjof Capra',
    price: 15.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '30',
    title: 'A Trégua',
    author: 'Mario Benedetti',
    price: 15.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '31',
    title: 'A Última Carta de Amor',
    author: 'Jojo Moyes',
    price: 12.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '32',
    title: 'Admirável Mundo Novo',
    author: 'Aldous Huxley',
    price: 10.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '33',
    title: 'Advanced Writing Skills',
    author: 'John Arnold & Jeremy Harmer (English version)',
    price: 3.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '34',
    title: 'Além da Globalização',
    author: 'Hazel Henderson',
    price: 7.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '35',
    title: 'Alicerce do Paraíso - volume 2',
    author: 'Meishu-Sama',
    price: 5.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '36',
    title: 'Almas Mortas',
    author: 'Nikolai Gógol',
    price: 25.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '37',
    title: 'Aprender e ensinar na escola vestida de branco: do modelo biomédico ao humanístico',
    author: 'Silva; Tsuji',
    price: 15.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '38',
    title: 'Aromaterapia: Aroma e Psiquê',
    author: 'Peter & Kate Damian',
    price: 40.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '39',
    title: 'As 5 Linguagens do Amor dos Adolescentes',
    author: 'Gary Chapman',
    price: 25.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '40',
    title: 'As Aventuras do Sr. Pickwick - volume 1',
    author: 'Charles Dickens',
    price: 12.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '41',
    title: 'As Aventuras do Sr. Pickwick - volume 2',
    author: 'Charles Dickens',
    price: 12.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '42',
    title: 'As Memórias do Livro: romance sobre o manuscrito de Saravejo',
    author: 'Geraldine Brooks',
    price: 32.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '43',
    title: 'As quatro estações do casamento',
    author: 'Gary Chapman',
    price: 18.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '44',
    title: 'As Relações Perigosas',
    author: 'Choderlos de Laclos',
    price: 22.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '45',
    title: 'Atrás do Espelho',
    author: 'A. G. Howard',
    price: 10.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '46',
    title: 'Autobiography of a Yogi',
    author: 'Paramahansa Yogananda (English version)',
    price: 12.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '47',
    title: 'Autoperfeição com Hatha Yoga',
    author: 'Hermógenes',
    price: 3.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '48',
    title: 'Babbitt',
    author: 'Sinclair Lewis',
    price: 22.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '49',
    title: 'Bom Dia, Espírito Santo',
    author: 'Benny Hinn',
    price: 15.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '50',
    title: 'Box After - volumes 1 ao 5',
    author: 'Anna Todd',
    price: 150.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '51',
    title: 'Budapest',
    author: 'Everyman Guides (English edition)',
    price: 15.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '52',
    title: 'Casa de Bonecas',
    author: 'Henrik Ibsen',
    price: 10.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '53',
    title: 'Bom R$15,00  Bom R$15,00 Ciência Hindu-Yogue da Respiração',
    author: 'Yogue Ramacharaca',
    price: 7.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '54',
    title: 'Cinquenta Tons de Cinza',
    author: 'E. L. James',
    price: 27.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '55',
    title: 'Cinquenta Tons Mais Escuros',
    author: 'E. L. James',
    price: 27.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '56',
    title: 'Clara dos Anjos',
    author: 'Lima Barreto',
    price: 10.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '57',
    title: 'Coleção Os Pensadores',
    author: 'Santo Agostinho',
    price: 20.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '58',
    title: 'Comer, Rezar, Amar',
    author: 'Elizabeth Gilbert',
    price: 23.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '59',
    title: 'Como eu era antes de você',
    author: 'Jojo Moyes',
    price: 10.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '60',
    title: 'Como Tornar-se Yogue',
    author: 'Swami Abhedananda',
    price: 5.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '61',
    title: 'Competindo pelo Futuro: estratégias inovadoras para obter o controle do seu setor e criar os mercados de amanhã',
    author: 'Gary Hamel e C. K. Prahalad',
    price: 18.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '62',
    title: 'Comunicação Integrada: teoria, legislação e exercícios',
    author: 'Alessandra Mendes Durante',
    price: 7.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '63',
    title: 'Constituição da República Federativa do Brasil',
    author: 'Coleção Saraiva de Legislação',
    price: 20.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '64',
    title: 'Contabilidade Aplicada ao Setor Público',
    author: 'Francisco Glauber Lima Mota',
    price: 10.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '65',
    title: 'Chile e Ilha de Páscoa: mapas fáceis de usar',
    author: 'Globo Livros Chile: Cien Días en la Historia del Siglo XX — Bárbara Silva e Josefina Cabrera (Edición en Español)Contabilidade de Custos — Eliseu Martins',
    price: 20.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '66',
    title: 'Convite à Não-Violência',
    author: 'Hermógenes',
    price: 8.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '67',
    title: 'Cozinha vegetariana: tortas salgadas',
    author: 'Caroline Bergerot',
    price: 8.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '68',
    title: 'Cura Prática pela Água',
    author: 'Yogue Ramacharaca',
    price: 9.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '69',
    title: 'Curso de Direito Administrativo',
    author: 'Celso Antônio Bandeira de Mello',
    price: 30.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '70',
    title: 'Curso de Gramática Aplicada aos Textos',
    author: 'Ulisses Infante',
    price: 10.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '71',
    title: 'Cyrano de Bergerac',
    author: 'Edmond Rostand',
    price: 10.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '72',
    title: 'Deus investe em você',
    author: 'Hermógenes',
    price: 8.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '73',
    title: 'Direito Administrativo',
    author: 'Gustavo Henrique Pinheiro de Amorim',
    price: 10.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '74',
    title: 'Direito Constitucional',
    author: 'Marcelo Galante',
    price: 10.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '75',
    title: 'Direito Previdenciário ESAF - Hugo Goes Bom R$30,00 Dublinenses',
    author: 'James Joyce',
    price: 20.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '76',
    title: 'El Vecino del Quinto',
    author: 'Lourdes Miquel e Nues Sans (Edición en Español)',
    price: 5.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '77',
    title: 'Estatística Aplicada à Administração',
    author: 'William J. Stevenson',
    price: 20.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '78',
    title: 'Estratégia Competitiva: técnicas para análise de indústrias e da concorrência',
    author: 'Michael E. Porter',
    price: 65.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '79',
    title: 'Eu me chamo Antônio',
    author: 'Pedro Gabriel',
    price: 5.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '80',
    title: 'Eugênia Grandet',
    author: 'Honoré de Balzac',
    price: 18.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '81',
    title: 'Exercícios',
    author: 'Hilda Hilst',
    price: 20.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '82',
    title: 'Fundamento e Técnica do Hatha Yoga',
    author: 'Antonio Blay',
    price: 10.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '83',
    title: 'Gestão do Conhecimento: estratégias competitivas para a criação e mobilização do conhecimento na empresa',
    author: 'Saulo Porfírio Figueiredo',
    price: 20.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '84',
    title: 'Ginástica Psico-física',
    author: 'Grande Fraternidade Universal',
    price: 5.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '85',
    title: 'Grande História Universal: O Renascimento',
    author: 'Autores diversos',
    price: 17.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '86',
    title: 'Grande História Universal: O Século XVI',
    author: 'Autores diversos',
    price: 17.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '87',
    title: 'Guia Criativo para o Viajante Independente na Europa',
    author: 'Zizo Asnis & Os Viajantes',
    price: 12.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '88',
    title: 'História da Riqueza do Homem',
    author: 'Leo Huberman',
    price: 10.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '89',
    title: 'Histórias de Amor',
    author: 'Rubem Fonseca',
    price: 12.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '90',
    title: 'Histórias Primordiais',
    author: 'Edgar Allan Poe',
    price: 15.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '91',
    title: 'Ideias sobre ideias: mais de 500 pensamentos inspiradores sobre criatividade',
    author: 'Roberto Menna Barreto',
    price: 18.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '92',
    title: 'Ilusões Perdidas',
    author: 'Balzac',
    price: 20.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '93',
    title: 'Índia: um olhar amoroso',
    author: 'Jean Claude Carrière',
    price: 42.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '94',
    title: 'Bom R$15,00  Bom R$32,00 Introdução à Sociologia',
    author: 'Reinaldo Dias',
    price: 30.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '95',
    title: 'Jnana-Yoga: Yoga da Sabedoria',
    author: 'Yogue Ramacharaca',
    price: 9.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '96',
    title: 'Karma: a Justiça Infalível',
    author: 'A. C. Bhaktivedanta Swami Prabhupada',
    price: 3.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '97',
    title: 'Krishna: o Reservatório de Prazer',
    author: 'Sociedade Internacional da Consciência de Krishna',
    price: 1.50,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '98',
    title: 'La Bodega',
    author: 'Noah Gordon',
    price: 23.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '99',
    title: 'Leia isto se quer tirar fotos incríveis',
    author: 'Henry Carroll',
    price: 28.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '100',
    title: 'Liberte-se do Passado',
    author: 'Krishnamurti',
    price: 12.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '101',
    title: 'Lolita',
    author: 'Vladmir Nabokov',
    price: 20.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '102',
    title: 'Inglaterra, Escócia e País de Gales: guia visual',
    author: 'Folha de S. Paulo Inteligência Emocional: A Teoria Revolucionária que Define o que é ser Inteligente — Daniel GolemanMemórias, Sonhos, Reflexões — Carl G. Jung',
    price: 40.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '103',
    title: 'Menino de Engenho',
    author: 'José Lins do Rego',
    price: 22.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '104',
    title: 'Mentes que amam demais: o jeito borderline de ser',
    author: 'Ana Beatriz Barbosa Silva',
    price: 25.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '105',
    title: 'Mentiras... ou não? Uma quase autobiografia',
    author: 'Turibio Santos',
    price: 5.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '106',
    title: 'Mentirosos',
    author: 'E. Lockhart',
    price: 12.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '107',
    title: 'Meus Exílios e 20 Saudades',
    author: 'Ana Amélia Gadelha Lins Cavalcante',
    price: 3.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '108',
    title: 'Mil Dias em Veneza',
    author: 'Marlena de Blasi',
    price: 7.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '109',
    title: 'Minidicionário Ruth Rocha Médio R$3,00 Moll Flanders',
    author: 'Daniel Defoe',
    price: 25.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '110',
    title: 'Mulheres Apaixonadas',
    author: 'D. H. Lawrence',
    price: 22.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '111',
    title: 'Na Era do Capital Humano',
    author: 'Richard Crawford',
    price: 10.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '112',
    title: 'Naná',
    author: 'Émile Zola',
    price: 28.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '113',
    title: 'Não Confunda!',
    author: 'Luiz Antonio Sacconi',
    price: 10.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '114',
    title: 'Nascimento da Era Caórdica',
    author: 'Dee Hock',
    price: 10.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '115',
    title: 'Neoliberal, não. Liberal: para entender o Brasil de hoje e de amanhã',
    author: 'Carlos Alberto Sandenberg',
    price: 8.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '116',
    title: 'Nhá Chica: a pérola de Baependi',
    author: 'Autores diversos',
    price: 12.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '117',
    title: 'No Caminho de Swann',
    author: 'Marcel Proust',
    price: 10.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '118',
    title: 'Nosso Homem em Havana',
    author: 'Graham Greene',
    price: 28.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '119',
    title: 'Nunca Desista de Seus Sonhos',
    author: 'Augusto Cury',
    price: 10.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '120',
    title: 'O Ateneu',
    author: 'Raul Pompéia',
    price: 20.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '121',
    title: 'O Canto Mais Escuro da Floresta',
    author: 'Holly Black',
    price: 14.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '122',
    title: 'O Corpo Fala: a linguagem silenciosa da comunicação não-verbal',
    author: 'Pierre Weil e Roland Tompakow',
    price: 18.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '123',
    title: 'O Diário de Anne Frank',
    author: 'Anne Frank',
    price: 10.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '124',
    title: 'O Espírito do Aikido',
    author: 'Kisshomaru Ueshiba',
    price: 8.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '125',
    title: 'O Essencial da Vida',
    author: 'Hermógenes',
    price: 5.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '126',
    title: 'O Falecido Mattia Pascal & Seis Personagens à Procura de um Amor',
    author: 'Pirandello',
    price: 12.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '127',
    title: 'O Faroleiro e outros contos',
    author: 'Henryk Sienkiewicz',
    price: 14.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '128',
    title: 'O Físico',
    author: 'Noah Gordon',
    price: 25.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '129',
    title: 'O Grande Conflito Bom R$10,00 O Grande Conflito Médio R$7,00 O Interesse Humano',
    author: 'N. Sri Ram',
    price: 5.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '130',
    title: 'O Lado Mais Sombrio',
    author: 'A. G. Howard',
    price: 10.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '131',
    title: 'O Livro de Areia',
    author: 'Jorge Luis Borges',
    price: 20.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '132',
    title: 'O Pêndulo de Foucault',
    author: 'Umberto Eco',
    price: 32.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '133',
    title: 'O Rei do Conhecimento',
    author: 'Raja Vidya',
    price: 3.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '134',
    title: 'O Sol também se Levanta',
    author: 'Ernest Hemingway',
    price: 20.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '135',
    title: 'Obra Selectas',
    author: 'Arthur Conan Doyle (Edición en Español)',
    price: 20.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '136',
    title: 'Obras Primas da Novela Brasileira',
    author: 'Autores diversos',
    price: 10.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '137',
    title: 'Parto Ativo: Guia Prático para o Parto Natural',
    author: 'Janet Balaskas',
    price: 27.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '138',
    title: 'Pawn Structure Chess',
    author: 'A. Soltis (English version)',
    price: 38.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '139',
    title: 'Placenta: o mais feminino de todos os remédios',
    author: 'Cornelia Enning',
    price: 15.00,
    cover_url: null,
    description: null,
    condition: 'novo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '140',
    title: 'Planejamento Estratégico na Prática',
    author: 'Adalberto A. Fischmann e Martinho Isnard R. de Almeida',
    price: 20.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '141',
    title: 'Poemas Escolhidos',
    author: 'Emily Dickinson',
    price: 8.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '142',
    title: 'Praga: o guia que lhe mostra o que os outros só contam',
    author: 'Guia American Express',
    price: 15.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '143',
    title: 'Quase Memória',
    author: 'Carlos Heitor Cony',
    price: 12.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '144',
    title: 'Rápido & saboroso: omeletes, crepes e fritos Médio R$5,00 Receitas práticas com verduras e legumes',
    author: 'Maria Luiza Favero',
    price: 10.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '145',
    title: 'Rumo à Estação Finlândia',
    author: 'Edmund Wilson',
    price: 15.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '146',
    title: 'Se não eu, quem vai fazer você feliz?',
    author: 'Graziela Gonçalves',
    price: 25.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '147',
    title: 'Simples e Sublime: culinária vegetariana para a vida moderna. Receitas saborosas, rápidas e fáceis de fazer',
    author: 'Isik Polater e Manju Patel',
    price: 15.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '148',
    title: 'Sociedade Pós-Capitalista',
    author: 'Peter Drucker',
    price: 10.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '149',
    title: 'Sri Guru Gita',
    author: 'Gurudev Siddha Peeth (English version)',
    price: 5.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '150',
    title: 'Star Wars: um novo amanhecer',
    author: 'John Jackson Miller',
    price: 18.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '151',
    title: 'Suave é a Noite',
    author: 'F. Scott Fitzgerald',
    price: 27.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '152',
    title: 'Teoria Geral do Processo Civil Contemporâneo',
    author: 'Humberto Dalla Bernardina de Pinho',
    price: 30.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '153',
    title: 'The Secret/O Segredo',
    author: 'Rhonda Byrne',
    price: 15.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '154',
    title: 'The Subtle Art of Not Giving a F*ck: a counterintuitive approach to living a good life',
    author: 'Mark Manson',
    price: 10.00,
    cover_url: null,
    description: null,
    condition: 'usado',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '155',
    title: 'Tom Jones',
    author: 'Henry Fielding',
    price: 20.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '156',
    title: 'Trem Noturno para Lisboa',
    author: 'Pascal Mercier',
    price: 18.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '157',
    title: 'Inteligência Emocional: A Teoria Revolucionária que Define o que é ser Inteligente',
    author: 'Daniel Goleman',
    price: 32.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '158',
    title: 'Memórias, Sonhos, Reflexões',
    author: 'Carl G. Jung',
    price: 40.00,
    cover_url: null,
    description: null,
    condition: 'seminovo',
    genre: null,
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
